# Libraries for Data Science

As mentioned before, python is a general purpose programming language.
What allowed python to become a favorite of data scientists, is the support of community developed libraries.
In this chapter, we will discuss introduce a some of these libraries.

## `numpy` 

The library `numpy` allows python to perform vectorized calculations and matrix operations.
It offers advanced features beyond the capabilities of built-in python lists and tuples.
It also provides a library of mathematical functions, random number generators, etc.
Compared to built-in functions, python is able to perform efficient calculations by leveraging C code.

### `ndarray`

NumPy relies on its own compound class called `ndarray` (which stands for n-dimensional array, sometimes also referred to as `array`). 
Here's a simple one-dimensional array, created using the constructor `array()`

In [1]:
import numpy as np

np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

You can create multidimensional arrays by providing the constructor with a nested list of numbers:

In [2]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

These `array` class comes with useful attributes such as:

- `shape` which represents the dimensions of the array
- `ndim` which represents the number of dimensions of the array 
- `dtype` which represents the datatype of the array's elements
- `size` which represents the number of elements in the array.

In [3]:
mat.shape

(2, 3)

In [4]:
mat.ndim

2

In [5]:
mat.dtype.name #use the dtype.name to show the string representation of the datatype

'int64'

In [6]:
mat.size

6

You can also create a NumPy array using other useful constructors:

In [7]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.arange(5, 20, 0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

When using arithmetic operations (`+`, `*`, `-`, `/`) on NumPy arrays, the operations are treated as element wise operations.

### NumPy Broadcasting

You can use these operations on any pair of arrays with compatible shapes.
Shape compatibility in NumPy works with respect to the NumPy broadcasting rules.
NumPy first compares number of dimensions, if the two operands have unequal dimensions, NumPy implicitly adds dimensions of size one to the left of the lower-dimensional operand.
For example, when attempting to perform operations on a pair of arrays with the shapes: $3 \times 4 \times 5$, and $5$, the second array is converted to a $1 \times 1 \times 5$ array.

With the number of dimensions settled, NumPy checks if each dimension has compatible sizes.
Sizes are compatible if they are equal or one of the sizes is exactly one.
If a dimension is exactly one, the array is "stretched" to accommodate the larger array.

For example, given:

In [10]:
A = np.arange(1,61).reshape((3,4,5)) # reshape is a method used change the dimensions of the array
B = np.array([1,2,3,4,5])

Since `B` has two dimensions, it is implicitly reshaped into a $1 \times 1 \times 5$ array.
Based on the broadcasting rules `A` and `B` of compatible sizes.
To accommodate the elements of `A`, the elements of `B` are stretched to a goal shape of $3 \times 4 \times 5$.
First, it is stretched into a $4 \times 5$ array by copying itself four times, similar to the following operation:

In [11]:
twoDimensions = np.array([B] * 4) # stretches using list multiplication
twoDimensions

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

The resulting array is then stretched 3 times to reach the goal shape $3 \times 4 \times 5$:

In [12]:
threeDimensions = np.array([twoDimensions] * 3)
threeDimensions

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

With the sizes now matching it applies the calculation.
You can compare the calculations indeed match:

In [13]:
print("product from automatic broadcasting:")
print(A * B)
print("product from explicit stretching")
print(A * threeDimensions)

product from automatic broadcasting:
[[[  1   4   9  16  25]
  [  6  14  24  36  50]
  [ 11  24  39  56  75]
  [ 16  34  54  76 100]]

 [[ 21  44  69  96 125]
  [ 26  54  84 116 150]
  [ 31  64  99 136 175]
  [ 36  74 114 156 200]]

 [[ 41  84 129 176 225]
  [ 46  94 144 196 250]
  [ 51 104 159 216 275]
  [ 56 114 174 236 300]]]
product from explicit stretching
[[[  1   4   9  16  25]
  [  6  14  24  36  50]
  [ 11  24  39  56  75]
  [ 16  34  54  76 100]]

 [[ 21  44  69  96 125]
  [ 26  54  84 116 150]
  [ 31  64  99 136 175]
  [ 36  74 114 156 200]]

 [[ 41  84 129 176 225]
  [ 46  94 144 196 250]
  [ 51 104 159 216 275]
  [ 56 114 174 236 300]]]

Here's another example involving an array of size $4$ and an array of size $5 \times 1$:

In [14]:
C = np.array([1,2,3,4])
D = np.array([1,2,3,4,5]).reshape((5,1))

To accommodate each other, both arrays are stretched into $4 \times 5$:

In [15]:
stretchedC = np.array([C] * 5)
stretchedD = np.repeat(D, 4, axis = 1) # stretches the column into 5 columns

print("product from automatic broadcasting")
print(C * D)
print("product from explicit stretching")
print(stretchedC * stretchedD)

product from automatic broadcasting
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]
product from explicit stretching
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]

NumPy also features special mathematical functions that can be applied to scalar values or arrays.
When applied to arrays these functions are applied element-wise.
These functions are known as universal functions (`ufunc`). You can find a reference of universal functions [here](https://numpy.org/devdocs/reference/ufuncs.html).

In [16]:
arr = np.arange(0,1,0.2)
print(np.sqrt(arr))
print(np.round(arr,10))
print(np.ceil(arr))

[0.         0.4472136  0.63245553 0.77459667 0.89442719]
[0.  0.2 0.4 0.6 0.8]
[0. 1. 1. 1. 1.]

Arrays in NumPy also support advanced indexing, including slicing, logical indexing, and iteration:

In [17]:
arr = np.arange(0,20)
print(arr[10:15])
print(arr[3:12:2])
print(arr[:5:-2])
print(arr[arr % 2 == 0])

[10 11 12 13 14]
[ 3  5  7  9 11]
[19 17 15 13 11  9  7]
[ 0  2  4  6  8 10 12 14 16 18]

## `pandas`

The `pandas` library features is used for all manners of data analysis tasks.
It features new classes like `DataFrame` and `Series`.
Behind the scenes it is also supported by `numpy`, allowing it to harness `numpy`'s vectorization and indexing.

### `Series`

The class `Series` is a core data structure in `pandas` used to represent vectors of any datatype.

There are multiple ways to construct a `Series` in the example below we create a series by passing a `numpy` array as an argument to the constructor.

In [18]:
import numpy as np
import pandas as pd

pd.Series(np.arange(100,601,100))

0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64

All `Series` objects come with indices.
By default, indices are set to $[0, n-1]$ for a series with n elements.
Indices can be any datatype, as long as the number of elements in the series match the number of elements in index.
You can think of indices as the dictionary keys and the elements themselves as the values.

In [19]:
pd.Series([10,1,2], index = ["a", "b", "c"])

a    10
b     1
c     2
dtype: int64

In [20]:
pd.Series([10,1,2], index = [True, False, True])

True     10
False     1
True      2
dtype: int64

> As shown above, indices don't need to be unique.
> But in most cases, you would want unique indices to avoid indexing issues.

A `Series` supports vectorized functions, element-wise operations and advanced indexing.
Doing these operations simply delegates it to the `numpy` behind the scenes.

In [21]:
s = pd.Series(np.arange(100, 601, 100), index = ["a","b","c","d","e","f"])
s[["b", "d", "a"]]

b    200
d    400
a    100
dtype: int64

In [22]:
print(s * 3)
print(s + s)
print(s[s % 200 == 0])

a     300
b     600
c     900
d    1200
e    1500
f    1800
dtype: int64
a     200
b     400
c     600
d     800
e    1000
f    1200
dtype: int64
b    200
d    400
f    600
dtype: int64

You can also use `numpy`'s universal functions on `Series` instances.
When you do this, the function will be applied element-wise.

```
np.sqrt(s)
```

Pandas will try to coerce the `Series` elements into numeric types when used on `ufunc`s.
If the elements can't be coerced, it will result into an error.

In [23]:
np.power(2,pd.Series([True, False, True]))

0    2
1    1
2    2
dtype: int64

Note that when performing element-wise operations involving multiple series, elements are not matched by position.
Instead, matching indices are paired up, and the operations are performed on each pair.

In [24]:
t = pd.Series([1,2,3,4], index = ["g", "f", "e", "c"])
s + t

a      NaN
b      NaN
c    304.0
d      NaN
e    503.0
f    602.0
g      NaN
dtype: float64

In the example above, to construct the sum of `s` and `t`, `s["c"]` and `t["c"]` are added, `s["e"]` and `t["e"]` are added and `s["f"]` and `t["f"]` are added.
Elements without a pair will have a sum of `NaN` which stands for "Not a Number".
If you want to exclude `NaN` elements, you can filter them out using the `dropna()` method.

In [25]:
(s + t).dropna()

c    304.0
e    503.0
f    602.0
dtype: float64

### `DataFrame`

`DataFrames` are representations of relational tables built by combining one or more `Series`.
Each `Series` in a `DataFrame` represents a table column.
All `Series` composed under one `DataFrame` are aligned under one index.

There are multiple ways to construct `DataFrames`.
The example below constructs a `DataFrame` from a given 2d array and a given column list.

In [26]:
df = pd.DataFrame(
    data = np.arange(10, 121, 10).reshape((3,4)), 
    columns = ["a","b","c","d"]
)

> Since an index was not specified, it will default to `[0,1,2]`.

When you apply `numpy`'s universal function on `DataFrame` instances, the functions are applied to each series in the `DataFrame`, coercing the types if necessary.

In [27]:
np.sqrt(df)

          a          b          c          d
0  3.162278   4.472136   5.477226   6.324555
1  7.071068   7.745967   8.366600   8.944272
2  9.486833  10.000000  10.488088  10.954451

When an operation involves two `DataFrame` instances, the operations are applied to pairs of elements with matching column names and indices.
Unpaired elements will evaluate to `NaN`.

In [28]:
df2 = pd.DataFrame(
    data = np.arange(0,6).reshape((2,3)), 
    columns = ["a","b","c"]
)
df + df2

      a     b     c   d
0  10.0  21.0  32.0 NaN
1  53.0  64.0  75.0 NaN
2   NaN   NaN   NaN NaN

You can retrieve entire columns of a `DataFrame` by indexing.
This retrieves a `Series` instance representing the column.

In [29]:
df["a"]

0    10
1    50
2    90
Name: a, dtype: int64

If you assign a new series instance to an existing column, the column will be replaced with the new `Series` instance.
Note that the new `Series`'s indices must match your `DataFrame`'s existing indices.
Unmatched indices will produce `NaN` values.

In [30]:
# the new series's indices will match df's default indices
df["a"] = pd.Series(np.zeros(3))
df

     a    b    c    d
0  0.0   20   30   40
1  0.0   60   70   80
2  0.0  100  110  120

In [31]:
# mismatched indices will produce NaN entries
df["a"] = pd.Series(np.ones(3), index = [4,5,6])
df

    a    b    c    d
0 NaN   20   30   40
1 NaN   60   70   80
2 NaN  100  110  120

Assigning to a non-existent column name will add a new column to the `DataFrame`.

In [32]:
df2

   a  b  c
0  0  1  2
1  3  4  5

In [33]:
df2["d"] = pd.Series(["new data1", "new data2"])

You can retrieve entire rows using the attribute `loc`.
This retrieves a `Series` instance with column names serving as the `Series` instance's index.

In [34]:
df2.loc[1]

a            3
b            4
c            5
d    new data2
Name: 1, dtype: object

To add new row, you can create new `DataFrame` containing one row and use the function `pd.concat()`.
In the example below, we create the new `DataFrame` from a list containing one dictionary.

In [35]:
row = pd.DataFrame([{"a":10, "b":20, "c":30, "d":40}], index = [len(df)])

extended_df = pd.concat([df, row])
extended_df

      a    b    c    d
0   NaN   20   30   40
1   NaN   60   70   80
2   NaN  100  110  120
3  10.0   20   30   40

> To avoid duplicates, make sure `row` uses new indices

You can also add more than one row, by adding more dictionaries in the list of dictionaries passed in the `DataFrame` constructor.

In [36]:
rows = pd.DataFrame([
    {"a":20, "b":30, "c":40, "d":50},
    {"a":10, "b":40, "c":50, "d":60}
], index = [len(extended_df), len(extended_df) + 1])

extended_df = pd.concat([extended_df, rows])
extended_df

      a    b    c    d
0   NaN   20   30   40
1   NaN   60   70   80
2   NaN  100  110  120
3  10.0   20   30   40
4  20.0   30   40   50
5  10.0   40   50   60

You can also add single rows by assigning a new index to the `loc` attribute.

In [37]:
extended_df.loc[len(extended_df)] = {"a":100, "b":100, "c":100, "d":100}
extended_df

       a    b    c    d
0    NaN   20   30   40
1    NaN   60   70   80
2    NaN  100  110  120
3   10.0   20   30   40
4   20.0   30   40   50
5   10.0   40   50   60
6  100.0  100  100  100

> If you want to retrieve a row based on its position, use the `iloc` attribute instead.

You can also use the same syntax to change existing rows.

In [38]:
extended_df.loc[0] = {"a":0, "b":0, "c":0, "d":0}
extended_df

       a    b    c    d
0    0.0    0    0    0
1    NaN   60   70   80
2    NaN  100  110  120
3   10.0   20   30   40
4   20.0   30   40   50
5   10.0   40   50   60
6  100.0  100  100  100

To retrieve a specific cell, you can combine retrieve an entire column as a `Series` instance and retrieve the specific element using `Series` indexing.

In [39]:
extended_df["b"][3]

np.int64(20)

Note, it is not advised to use this to change the value of a cell since `extended["b"]` is just a copy of a slice from the original `DataFrame`, `df2`.
Pandas warns you about the caveats of this.

In [40]:
extended_df["b"][1] = -1
extended_df

/tmp/ipykernel_50720/992917263.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  extended_df["b"][1] = -1

       a    b    c    d
0    0.0    0    0    0
1    NaN   60   70   80
2    NaN  100  110  120
3   10.0   20   30   40
4   20.0   30   40   50
5   10.0   40   50   60
6  100.0  100  100  100

Instead, use the `at` attribute to change the cell

In [41]:
extended_df.at[1, "b"] = -1
extended_df

       a    b    c    d
0    0.0    0    0    0
1    NaN   -1   70   80
2    NaN  100  110  120
3   10.0   20   30   40
4   20.0   30   40   50
5   10.0   40   50   60
6  100.0  100  100  100

## `matplotlib`